--ex1 
SELECT NAME FROM STUDENTS
WHERE MARKS > 75
ORDER BY RIGHT(NAME,'3'),ID 
--ex2
SELECT USER_ID,CONCAT(UPPER(SUBSTRING(NAME,1,1)),LOWER(SUBSTRING(NAME,2))) AS NAME FROM USERS 
--EX3
SELECT MANUFACTURER,CONCAT('$'|| ROUND(SUM(TOTAL_SALES)/1000000,0) || ' MILLION') AS SALE_MIL FROM pharmacy_sales
GROUP BY MANUFACTURER
ORDER BY SUM(TOTAL_SALES) DESC;
--EX4
SELECT EXTRACT(MONTH FROM SUBMIT_DATE) AS MTH,PRODUCT_ID,ROUND(AVG(stars),2) FROM reviews
GROUP BY MTH,PRODUCT_ID
ORDER BY MTH,PRODUCT_ID;
--EX5
SELECT SENDER_ID,COUNT(MESSAGE_ID) AS MESSAGE_COUNT FROM messages
WHERE EXTRACT(MONTH FROM SENT_DATE) = 08 AND EXTRACT(YEAR FROM SENT_DATE)= '2022'
GROUP BY SENDER_ID
ORDER BY MESSAGE_COUNT DESC
LIMIT 2;
--EX6
SELECT TWEET_ID FROM TWEETS
WHERE LENGTH(CONTENT) > 15;
--EX7

--EX8
select COUNT(ID) AS EMPLOYEE from employees
WHERE EXTRACT(MONTH FROM JOINING_DATE) IN (1,2) AND EXTRACT(YEAR FROM JOINING_DATE) = 2022;
--EX9
SELECT POSITION('A' IN FIRST_NAME) FROM WORKER
WHERE FIRST_NAME = 'Amitah';
--EX10
